### ISSUE TITLE
Support Deno 1.4.0 stricter type checks

### ISSUE THREAD

**Issue by asos-craigmorten** [garronej/evt#12]
**Is your feature request related to a problem? Please describe.**

Deno 1.4.0 introduced stricter type checks for all users using the `--unstable` flag. These (presumably) will be integrated with Deno stable in an upcoming release. This request is to make the necessary changes to support these stricter checks.

See relevant section in release blog post: https://deno.land/posts/v1.4#stricter-type-checks-in-code--unstablecode

Specifically r.e. import and export of types.

**Describe the solution you'd like**

Import and export all types using the stricter syntax:

```ts
// Bad
import { MyType } from "./mod.ts";
export { MyType } from "./mod.ts";

// Good
import type { MyType } from "./mod.ts";
export type { MyType } from "./mod.ts";
```

**Describe alternatives you've considered**

--

**Additional context**

GitHub release notes 1.4.0: https://github.com/denoland/deno/releases/tag/v1.4.0

Faced the following errors when attempting to upgrade [Opine](https://github.com/asos-craigmorten/opine/pull/70) to use Deno 1.4.0 and run an example using unstable APIs. These errors should stand as a good starting point for finding all places which require changes:

```console
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { AsyncReturnType } from "./AsyncReturnType.ts";
         ~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/tools/typeSafety/index.ts:2:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackPromise } from "./UnpackPromise.ts";
         ~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/tools/typeSafety/index.ts:8:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackTypeGuard } from "./UnpackTypeGuard.ts";
         ~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/tools/typeSafety/index.ts:9:10

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Operator } from "./Operator.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/Handler.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Handler } from "../Handler.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/CtxLike.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Operator } from "../Operator.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/StatefulReadonlyEvt.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Handler } from "../Handler.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/NonPostableEvt.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Operator } from "../Operator.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/NonPostableEvt.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Handler } from "../Handler.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/Ctx.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Handler } from "../Handler.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/VoidCtx.ts:2:1

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Ctx, DoneOrAborted } from "./Ctx.ts";
         ~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:1:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Ctx, DoneOrAborted } from "./Ctx.ts";
              ~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:1:15

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { CtxLike, VoidCtxLike } from "./CtxLike.ts";
                  ~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:2:19

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Evt } from "./Evt.ts";
         ~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:3:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { NonPostableEvt } from "./NonPostableEvt.ts";
         ~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:4:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Postable } from "./Postable.ts";
         ~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:5:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { StatefulEvt } from "./StatefulEvt.ts";
         ~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:6:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { StatefulReadonlyEvt, StateDiff as Diff } from "./StatefulReadonlyEvt.ts";
         ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:7:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { StatefulReadonlyEvt, StateDiff as Diff } from "./StatefulReadonlyEvt.ts";
                              ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:7:31

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { StatefulPostable } from "./StatefulPostable.ts";
         ~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:8:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { VoidCtx } from "./VoidCtx.ts";
         ~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:9:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { VoidEvt } from "./VoidEvt.ts";
         ~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/interfaces/index.ts:10:10

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { SwapEvtType } from "./SwapEvtType.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/helper/FactorizeEvt.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { UnpackEvt } from "./UnpackEvt.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/helper/FactorizeEvt.ts:3:1

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { FactorizeEvt } from "./FactorizeEvt.ts";
         ~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/helper/index.ts:1:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { SwapEvtType } from "./SwapEvtType.ts";
         ~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/helper/index.ts:2:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { ToPostableEvt } from "./ToPostableEvt.ts";
         ~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/helper/index.ts:3:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { ToNonPostableEvt } from "./ToNonPostableEvt.ts";
         ~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/helper/index.ts:4:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackCtx } from "./UnpackCtx.ts";
         ~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/helper/index.ts:5:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackEvt, EvtLike } from "./UnpackEvt.ts";
         ~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/helper/index.ts:6:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { UnpackEvt, EvtLike } from "./UnpackEvt.ts";
                    ~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/helper/index.ts:6:21

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Handler } from "./Handler.ts";
         ~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/types/index.ts:5:10

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Operator } from "../../types/Operator.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/util/genericOperators/to.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { FactorizeEvt } from "./types/helper/FactorizeEvt.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.factorize.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { UnpackEvt } from "./types/helper/UnpackEvt.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.merge.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import * as dom from "./types/lib.dom.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.from.ts:7:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { ToPostableEvt } from "./types/helper/ToPostableEvt.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.asPostable.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { UnpackEvt } from "./types/helper/UnpackEvt.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.asyncPipe.ts:3:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { SwapEvtType } from "./types/helper/SwapEvtType.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.asyncPipe.ts:4:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { ToNonPostableEvt } from "./types/helper/ToNonPostableEvt.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.asNonPostable.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Handler } from "./types/Handler.ts"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.parsePropsFromArgs.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Operator } from "./types/Operator.ts"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.parsePropsFromArgs.ts:3:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { SwapEvtType } from "./types/helper/SwapEvtType.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.loosenType.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { UnpackEvt } from "./types/helper/UnpackEvt.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.loosenType.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Handler } from "./types/Handler.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Evt.ts:29:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { CtxLike } from "./types/interfaces/CtxLike.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/StatefulEvt.ts:9:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Handler } from "./types/Handler.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/evt@v1.8.9/lib/Ctx.ts:7:1
```

Happy to try to submit a PR 😄

**Comment by garronej** [comment]
Hey @asos-craigmorten, what's up?

This is great news, `import types` was introduced in TypeScript 3.8 just [as a little sintaxic shugar to cope with some problematic usecases](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export).  
In my opinion it is a major feature! Importing type only helps prevent requires circles and improve readability.  
The previous syntax was orible as for generic types we had to redeclare what the types arguements extends and it was easy to make a spelling mistake. e.g: `type MyTypes<T extends MyOtherType> = import("./MyType").MyType<T>;` 👎  

So I am very happy that this feature is being fully acknoleaged and made mandatory. 

It is not the first time I feel that the TypeScript team does not fully grasp how usefull some features are. `namespace` is an other example.

Now to our business. Unfortunately Denoify is not smart enough yet to tell, when there is an import if the token being imported is a type definition or something tangible. 
To be able to perform such a check we would have to use something like [TS-MORPH](https://github.com/dsherret/ts-morph) to parse the TypeScript sources.
I started Denoify as a quick hack and it is still parsing files using Regexp 🚨 .   

As a consequence I am afraid that the sources TS files have to be modified manually for now. I will fix EVT tonight ( unfortunately I can'u use `import type` in EVT as I committed to supporting TypeScript down to 3.4 so no `import type` can appear in the `.d.ts` files).

Of course I will hapilly accept your contribution but this particular feature looks like a lot of work to me...

**Comment by garronej** [comment]
@asos-craigmorten Sorry my mistake, I though this was an issue submitted on the Denoify repo....

**Comment by garronej** [comment]
@asos-craigmorten Wellcome to the contributor list.
![image](https://user-images.githubusercontent.com/6702424/93147992-046d9e00-f6f3-11ea-8a01-ce0fda79ea65.png)

Thank you your PR helped me a lot!

**Comment by garronej** [comment]
@asos-craigmorten And it's fixed, we can now use the `--unsafe` flag.
